language: script
script:
- mkdir redist && cd redist
- wget https://github.com/jomof/cdep/releases/download/alpha-0.0.68/redist.zip
- unzip redist.zip
- cd ..
- redist/cdep wrapper
- ./cdep create hashes
- cat cdep.sha256
- ./cdep

